name: Conda Environment Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12.1
        environment-file: environment.yml
        activate-environment: crypto-data

    - name: Install dependencies
      run: |
        conda info
        conda list

    - name: Install Package
      run: pip install -e .        

    - name: Run tests
      shell: bash -l {0}
      run: |
        python -m unittest discover -s tests  # Adjust based on your test structure
